from typing import Mapping, Optional
from zdx_parallel_vm import ParallelPyxelVM, SimpleCompiler

class SpatialRegion:
    name: str
    x: int
    y: int
    width: int
    height: int
    kind: str
    @property
    def cells(self) -> int: ...
    @property
    def capacity_bytes(self) -> int: ...
    def contains(self, x: int, y: int) -> bool: ...

class SpatialLayout:
    width: int
    height: int
    execution_rows: int
    regions: tuple[SpatialRegion, ...]
    @property
    def execution_region(self) -> SpatialRegion: ...
    @property
    def storage_region(self) -> SpatialRegion: ...
    @property
    def total_cells(self) -> int: ...
    @property
    def raw_capacity_bytes(self) -> int: ...
    @property
    def storage_capacity_bytes(self) -> int: ...
    def region(self, name: Optional[str] = ...) -> SpatialRegion: ...
    def address(self, x: int, y: int) -> int: ...
    def coordinates(self, address: int) -> tuple[int, int]: ...
    def to_dict(self) -> dict: ...

class SpatialFrame:
    layout: SpatialLayout
    @classmethod
    def blank(cls, layout: SpatialLayout) -> "SpatialFrame": ...
    @classmethod
    def open(cls, path: str, layout: SpatialLayout) -> "SpatialFrame": ...
    def read_cell(self, x: int, y: int) -> tuple[int, int, int]: ...
    def write_cell(self, x: int, y: int, rgb: tuple[int, int, int]) -> None: ...
    def read_u24(self, x: int, y: int) -> int: ...
    def write_u24(self, x: int, y: int, value: int) -> None: ...
    def read_bytes(self, length: int, *, region: Optional[str] = ..., offset: int = ...) -> bytes: ...
    def write_bytes(self, data: bytes, *, region: Optional[str] = ..., offset: int = ...) -> None: ...
    def write_json(self, obj, *, region: Optional[str] = ...) -> None: ...
    def read_json(self, *, region: Optional[str] = ...): ...
    def save(self, path: str) -> str: ...

class SpatialCompiler:
    layout: SpatialLayout
    compiler: SimpleCompiler
    def __init__(self, layout: SpatialLayout, compiler: Optional[SimpleCompiler] = ...) -> None: ...
    def compile(self, program: list, out_path: str, *, payloads: Optional[Mapping[str, object]] = ..., debug: bool = ...) -> str: ...
    def capacity_report(self) -> dict: ...

class SpatialPyxelVM(ParallelPyxelVM):
    layout: SpatialLayout
    def __init__(self, layout: Optional[SpatialLayout] = ..., **kwargs) -> None: ...
    def execute_spatial(self, image_path: str) -> dict: ...
    def open_spatial_frame(self, image_path: str) -> SpatialFrame: ...
    def spatial_address(self, x: int, y: int) -> int: ...
    def storage_read_bytes(self, image_path: str, length: int, *, region: Optional[str] = ..., offset: int = ...) -> bytes: ...
    def storage_write_bytes(self, image_path: str, data: bytes, *, region: Optional[str] = ..., offset: int = ...) -> str: ...
