from typing import Any, Optional

class ZDXAgentMemory:
    agent_id: str
    spatial: bool

    def __init__(
        self,
        agent_id: str = ...,
        base_dir: str = ...,
        *,
        spatial: bool = ...,
        spatial_width: int = ...,
        spatial_height: int = ...,
        spatial_execution_rows: int = ...,
    ) -> None: ...

    def remember(self, key: str, value: Any) -> str: ...
    def recall(self, key: str, default: Any = ...) -> Any: ...
    def forget(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def keys(self) -> list: ...
    def snapshot(self) -> dict: ...
    def update(self, data: dict) -> None: ...
    def clear(self) -> None: ...
    def append(self, key: str, item: Any) -> None: ...
    def recall_list(self, key: str) -> list: ...

    @property
    def capacity_bytes(self) -> Optional[int]: ...
