from typing import Any

class SpatialPixelStore:
    path: str
    layout: Any

    def __init__(
        self,
        path: str = ...,
        *,
        width: int = ...,
        height: int = ...,
        execution_rows: int = ...,
    ) -> None: ...

    @property
    def capacity_bytes(self) -> int: ...
    def write(self, key: str, value: Any) -> str: ...
    def read(self, key: str, default: Any = ...) -> Any: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...
    def keys(self) -> list: ...
    def all(self) -> dict: ...
    def clear(self) -> None: ...
